version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: nest-rxjs-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    # restart: always

volumes:
  redis-data: